app_music_file:
    resource: "@AppBundle/Controller/MusicFileController.php"
    type:     annotation

homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

login_check:
    path: /login_check
    defaults: { _controller: AppBundle:Security:check }

registration:
    path: /registration
    defaults: {_controller: AppBundle:RegistrationAndLogin:register}

music:
    path: /music
    defaults: {_controller: AppBundle:Music:index}

music_controll:
    path: /mc
    defaults: {_controller: AppBundle:Music:handleAjaxControll }

media:
    path: /media
    defaults: {_controller: AppBundle:Media:index}

music_libary:
    path: /media/music
    defaults: {_controller: AppBundle:Media:music}
