<?php
/**
 * Created by PhpStorm.
 * User: molnar.mate
 * Date: 2018.03.11.
 * Time: 17:05
 */
declare(strict_types=1);

namespace AppBundle\Manager;

use AppBundle\Util\ValueObject\Mp3TagObject;
use Doctrine\Common\Persistence\ObjectManager;

class MusicManager extends BaseManager
{
    public function __construct(ObjectManager $orm, string $class)
    {
        parent::__construct($orm, $class);
    }

    public function createNewWithData(Mp3TagObject $data): void
    {
        /**@var \AppBundle\Entity\MusicFile $music*/
        $music= parent::createNew(); // TODO: Change the autogenerated stub
        $music->setTitle(utf8_encode($data->getSongData()['song']));
        $music->setAuthor($data->getSongData()['artist']);
        $music->setPath($data->getPath());
        $music->setSize($data->getSize());
        $music->setDuration($data->getDuration());
        $this->updateEntity($music,true);
        var_dump($music);
    }
}